---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(threejs)
library(rgdal)
library("maptools")
library("maps")
library("writexl")
library("leaflet")
library(RColorBrewer)

#data sets
vaccines <- read.csv("~/covid-vaccines/CSVs/country_vaccinations_by_manufacturer.csv")

countries <- vaccines %>%
  group_by(location, vaccine) %>%
  summarise(
    vaccines_by_manu = sum(total_vaccinations)
  )

```

```{r}
#create the globe

#really cool github documentation for three.js 
# https://bwlewis.github.io/rthreejs/globejs.html 

earth <- system.file("images/world.jpg",  package = "threejs")

earth <- "http://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73909/world.topo.bathy.200412.3x5400x2700.jpg"
globejs(img = earth)


#uses better picture of earth but it's not currently running 
#earth_better <- system.file("~/covid-vaccines/images/earthmap.jpg", package = "threejs")

globejs(img = earth_better)

#will use the .json to outline countries
countryOutlines <- rgdal::readOGR( "~/covid-vaccines/data/countries.geo.json", layer = "countries.geo") 
                                              
#want to plot lat lon points on each country, use globejs 
#show vaccines by Pfizer 
Pfizer <- countries %>%
  filter(vaccine == "Pfizer/BioNTech")

Moderna <- countries %>%
  filter(vaccine == "Moderna")

OxfordAZ <- countries %>%
  filter(vaccine == "Oxford/AstraZeneca")

#filter JJ 
countries_fixedJJ <- read_csv("~/covid-vaccines/CSVs/countries_fixedJJ.csv") %>%
  subset(select = -c(X1)) %>%

JJ <- countries_fixedJJ %>%  
 filter(vaccine == "JJ")

cansino <- countries %>% 
  filter(vaccine == "CanSino")

sinovac <- countries %>%
  filter(vaccine == "Sinovac")

sinopharmBeijing <- countries %>% 
  filter(vaccine == "Sinopharm/Beijing")

SputnikV <- countries %>% 
  filter(vaccine == "Sputnik V")

write.csv(countries, "~/covid-vaccines/CSVs/countries.csv")
write.csv(world.cities,"~/covid-vaccines/CSVs/worldcities.csv")
write.csv(Pfizer, "~/covid-vaccines/CSVs/pfizer.csv")
write.csv(Moderna, "~/covid-vaccines/CSVs/moderna.csv")
write.csv(OxfordAZ, "~/covid-vaccines/CSVs/oxfordAZ.csv")
write.csv(JJ, "~/covid-vaccines/CSVs/jj.csv")
write.csv(cansino, "~/covid-vaccines/CSVs/cansino.csv")
write.csv(sinovac, "~/covid-vaccines/CSVs/sinovac.csv")
write.csv(sinopharmBeijing, "~/covid-vaccines/CSVs/jj.csv")
write.csv(SputnikV, "~/covid-vaccines/CSVs/sputnikV.csv")

#write as excel and manipulate what we want to keep from world cities and combine with Pfizer data and reupload 
worldcities_pfizer <- read.csv("~/covid-vaccines/CSVs/worldcities_pfizer.csv")
#read xlsx is not working
worldcities_OxfordAZ <- read.csv("~/covid-vaccines/CSVs/worldcities_OxfordAZ.csv")
worldcities_OxfordAZ_mutatelatlong <- subset(worldcities_OxfordAZ, select = -c(lat, long))
names(worldcities_OxfordAZ_mutatelatlong)[4] <- paste("lat")
names(worldcities_OxfordAZ_mutatelatlong)[5] <- paste("long")

#will eventually use the combined data set worldcities_all_manu and allow the user interface to filter by manufacturer

#pfizer globe
data(worldcities_pfizer, package="maps")
cities <- worldcities_pfizer[order(worldcities_pfizer$vaccines_by_manu,decreasing=TRUE)[1:37],]
value  <- 100 * cities$vaccines_by_manu / max(cities$vaccines_by_manu)

globejs(bg="black", lat=cities$lat,     long=cities$long, value=value, 
        rotationlat=-0.34,     rotationlong=-0.38, fov=30)


#pfizer and AZ globe
pfizer_AZ_join_mutatelatlong <- bind_rows(worldcities_pfizer, worldcities_OxfordAZ_mutatelatlong)

data(pfizer_AZ_join_mutatelatlong, package="maps")
cities_join_mut <- pfizer_AZ_join_mutatelatlong[order(pfizer_AZ_join_mutatelatlong$vaccines_by_manu,decreasing=TRUE)[1:37],]
value_join_mut  <- 100 * cities_join_mut$vaccines_by_manu / max(cities_join_mut$vaccines_by_manu)


#use dataset with all manufacturers
#filter by manufacturer
#color by rank_by_manufacturer
worldcities_rank_by_manu <- read.csv("~/covid-vaccines/CSVs/worldcities_rank_by_manu.csv")

pfizer_ranked <- worldcities_rank_by_manu %>%
  filter(vaccine == "Pfizer/BioNTech")


data(pfizer_ranked, package="maps")
cities <- pfizer_ranked[order(pfizer_ranked$vaccines_by_manu,decreasing=TRUE)[1:37],]
value  <- 100 * cities$vaccines_by_manu / max(cities$vaccines_by_manu)
palette = display.brewer.pal(9, YlOrRd)
colors = palette[pfizer_ranked$rank_by_manu]


globejs(bg="black",
        lat=cities$lat,
        long=cities$long, 
        value=value, 
        color=colors
        rotationlat=-0.34, 
        rotationlong=-0.38, 
        fov=30)


  
```

```{r}
##objective 
#Make a heat map by country for the number of vaccines distributed by manufacturer in each country. Let shiny pick a drop down for vaccine manufacturer and the output is a global heat map where color indicates the total number of vaccines distributed 

countryOutlines <- rgdal::readOGR( "~/covid-vaccines/data/countries.geo.json", layer = "countries.geo")

#use leaflet instead of globejs 

TCountriesGeo <- rgdal::readOGR( "data/countries.geo.json"
                               , "OGRGeoJSON"
                                )
TCountriesGeo@data <- TCountriesGeo@data %>%
                         left_join( ThreatenedClass
                         , by = c( "name" = "country"
                                  )
                                  )
                                              
                      pal <- colorNumeric( "YlOrRd"
                           , c( min(worldcities_pfizer$vaccines_by_manu
                                    )
                              , max( worldcities_pfizer$vaccines_by_manu
                                   )
                              )
                                          )



# https://data4help.medium.com/how-to-create-country-heatmaps-in-r-dbfe5ad6e2f1
#spike globe code: 
# https://bwlewis.github.io/rthreejs/globejs.html 
```

